LOCAL_PATH := $(call my-dir)
LIBRETRO_SWITCH=1
BAKE_IN_FFMPEG=1
LIBS:=
GLFLAGS:=

include $(CLEAR_VARS)

LOCAL_MODULE := retro

ROOT_DIR := ..
LIBRETRO_DIR = ../libretro
CORE_DIR := $(ROOT_DIR)

ifeq ($(TARGET_ARCH),arm)
LOCAL_ARM_MODE := arm
LOCAL_CFLAGS := -marm

COMMON_FLAGS := -DANDROID_ARM

ifeq ($(TARGET_ARCH_ABI), armeabi-v7a)
LOCAL_ARM_NEON := true
HAVE_NEON := 1
endif

endif

ifeq ($(TARGET_ARCH),x86)
COMMON_FLAGS := -DANDROID_X86 -D__SSE2__ -D__SSE__ -D__SOFTFP__
endif

ifeq ($(TARGET_ARCH),mips)
COMMON_FLAGS := -DANDROID_MIPS
endif

ifeq ($(NDK_TOOLCHAIN_VERSION), 4.6)
COMMON_FLAGS += -DANDROID_OLD_GCC
endif

SOUECES_C   :=
SOURCES_CXX :=
SOURCES_ASM :=
INCFLAGS    :=

include $(ROOT_DIR)/Makefile.common

LOCAL_SRC_FILES := $(SOURCES_CXX) $(SOURCES_C) $(SOURCES_ASM)

# Video Plugins

COMMON_FLAGS += -D__LIBRETRO__ -DINLINE="inline" -DANDROID $(DEFINES)
COMMON_OPTFLAGS = -O2

LOCAL_CFLAGS += $(COMMON_OPTFLAGS) $(COMMON_FLAGS) -std=gnu99 $(INCFLAGS) $(GLFLAGS)
LOCAL_CXXFLAGS += $(COMMON_OPTFLAGS) $(COMMON_FLAGS) $(INCFLAGS) $(GLFLAGS)
#LOCAL_LDLIBS += -lGLESv3
LOCAL_C_INCLUDES = $(INCFLAGS)

include $(BUILD_SHARED_LIBRARY)

